name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        env:
          BASE_PATH: ${{ secrets.BASE_PATH }}

      - run: |
          [ $BASE_PATH ] || BASE_PATH="/${REPO_NAME}"
          [ "$BASE_PATH" != "/g-web" ] && sed -i "s|/g-web|$BASE_PATH|g" /apps/demo/src/package.json

      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js rebuild --verbose

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: apps/demo/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
